language: java
jdk:
- openjdk10
env:
  global:
  - secure: X6i5a2uMK+w8Pr6Z10XKFGIsY1lOLAzZgquuaf4/k26NNSVmNb1YwcDSwWOJrns0ExmfCbL5l5rpeBVun3+uKr4dScVeptmAXpean8SuF8PvCHXPqM5KX3MM2Jc+2hLal3z/H+3PsDrPhLl0r8ooouUdmIgHvIEB4hdylLFGmmayr1F74I47hqhZYJbnIegjgfXKw3PiJc9y4z8GjUT+V0SMJQur9ZSrkweN/l3qxxuxREVYr05jS/dI9fwO9VUqF0P9VkoG2KOVnxWoOp+ip4ojvzqwawdDZg11cbcSla1dQwzNEvX4L1qycCok0pLOGMPkVqktWWSAdU5qMNh1ZbJ5TCd7Recv7npN8wCj1iGuj0ArR3Gs8RsLDV/P+i2WFqVz5y9Qp8rzn+ypfyOPIANRQg3l1ZS4GhkLWz+O6kc/9xFgF/BpCbOlTUzlBsSPc7nIKcJVRVULeMjCFJOBNEmPhCSb9Z+T807e2NOmKJe/GLbMEawajJNWclIiuHUniMS2Kl0NcakZva7RAJdnRWwqCtzrjgaj7jtvYFAipaEvQ2NeomRi9L/wpmqjTPLpv7JPRXr8/KSWg0mvViYnNF0rxoUN0BA8xJOrHZALFEx1WbD6P+dgOBeZcxtYTC3xWvSpXkacfWzJJgxEjVjtt3fn/HQ70mk6hLFvgOvdc6I=
  - secure: NdDxED8PShXWNveKy7pjXTVQ1mU/MPyFtjFy4MxiT4qEihvcaFoytf8oaZTHTlGT88/AwMQ3fkJlMHHiPm33pp28YWoIjE0+O4QciZTFKTQY2ixmECXoBWrxd7sneaUELQ1tnaDyLHYTpHxgRy9d0BmidEqRK15ZLLwIpvKTHLnqWDdWxiItusESldXWYhNf/q7bm97+tJ2eNUSShZFPy3IysFb7Re7yFGVjkWEDuy1ZA/RPlNaHgbioSn7xKGE11haEhRHV9Ff1onGPmpSHWFOkN21hIcovwkqEVfqzV/Nw418GRQb8r599fkqEflSeoe1WSDc0QZKRFpflN2KTVG3Nza7uAu0nfNXf5CLiAo5Xkx88K6BSQpofWSU/dT4grEFW1Rd7DMaYbR4dGRSKKCcqj/n1zggnyoc5+CmwxPis6hak7fjoKsj19UfeQsME33sVO1I9N4YFVj5LI4tipycZ20i6m+YZoXKFhT/8O5gKx9KFo7YLTHLudcfte1iW0BusCKG3gDFX9KCc5Tf86Auv26vkYAquliIQ7whAGoSKHxY12CYZ7q3AtWDyZ8KS8NQ9kFLeCVVKxiBA8HYojgh6QQEV5Q7keqShKM8c77sM87WLA6epXQEGzSrx76CvKF0mCrxxsMCUbn6h31dWs2nAxghPQxqmfT7b6BqlvY4=
  - secure: 0CqSuBjCSAosSdhxL7oKmscmy4MXq/pNEYF9Jjwwb2Knyr0soATyOW2aSM80GaAwtv4vSzW7awr4uzswXITUOBq4gT3gaxLoDCRFNpTZh02lNmjJc5vzUmTskDH8mh+EelZq4wPtYf81shvbWxcot0QZ1HErdMe0OCjvwHoc3T2T2kq/Th2t+nNGgezDYkjE024Ndb/FfBdRZ8xCycjpjLQUY1xmTxcZcCrwsbQod/MI0rSaLEjQ66W7p38WCVUM+VIjLr6zJbUhRLNKrMu9TvXpS6cDPNalmJiFjQwwHWc7ltWGF62GdgV/jkVdiOF2KhmOO3/B6EqV78y+nuqYJgJExzRbIz38qGEep/gs0D5lBbeabYix52w69XWg8bnnlTKjKCiTC/HcU8ldeje27Q91T6bfeyLQ8F8rpRohqJPbMi1VMuOQ4zwi0z5g/CfwLhnvg6mhGo8aeBgU3zYWPrMyHGbZykprWS1S/occsY+O8npNzmLfd3eXMU97FzrhgMcNmmzOnFkZYg+IgWi4a7wqv2jHX76GY+adcecG9FCPrIRVCpsRh2okkwSQdFdCnIfPq09El3bsXQ/Ycsc3OT3hLe4qmoBIGxRBSAG73FQvDoHaEsKZcgdf0XVfnwwPSDTZyJWtRHS/oYLzEDVug5nSIfrEhoOVb/hAEMsZNWk=
  - secure: BCRIabUOXsONffGgeXorRL5Cqmplfe01Y6FX+HzQWduCV/qjdOJumODaeVYWMMSuiw4MMn8GtdS4cwcCRMBia7vfKjyUWW4WEQ4T8HR0Ec4XzGiVbB7HwehPTyqdqUZs8J3Un8XiprqDMWJHJaZsSflGCVocFmDCPGWDWgDV+ZJQHJHPVBMtodTgNEr3dMQB5HVa7bN6DDB9eUGdWdVG+DyQwBAgl9stBwX4gXyuqOSU9FGQWvqWVY1E1n9H7msYV20uzZ1v64Ivxp1ieF60py6oPr2F2NR6tfwhwtYp09UDJ1swHsxPowl81Qmm4pq4GPQfxDmkR/fXBqT4N+a6vzmXj6zriPWH9ojiv9wm98F4bXlvPnTRnp6+Bj2IlVaPmBfxm4Sn+I4BDzA86uVOA6jKKmzOcT1qhBoS2gSw3Ib2PwW7DpA9sMCJsEzIxW0DqkAvmO3UFgmXfUOBYOSUueudszkf4BfZqfUoFiwyK4ZmqWZpMKWbCuKSBRWc7fIwzfKJrZA0nThSDP/CCi+L7LAt3yccI8QThHEFvtlHwNjIYQcwKAkvaI4HKkqMFf46WcgNNCHs2HrcK4SFaGgBsPwDk4h1s1VjicMOT/qRV4g8DLIuP7JOCUOz+mXDlPvqw8h8fNX+j2+r3CtdysAq9hwoUJ0wuysfA0sV49cP4WI=
install: "/bin/true"
script:
- "./test"
before_deploy:
- openssl aes-256-cbc -K $encrypted_8a0be36f8ed7_key -iv $encrypted_8a0be36f8ed7_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
deploy:
-
  skip_cleanup: true
  provider: script
  script: ./deploy
  on:
    branch: master
-
  skip_cleanup: true
  provider: script
  script: ./deploy
  on:
    tags: true
