/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.liveramp.generative;


public enum Color implements org.apache.thrift.TEnum {
  RED(1),
  BLUE(2),
  GREEN(3);

  private final int value;

  private Color(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Color findByValue(int value) { 
    switch (value) {
      case 1:
        return RED;
      case 2:
        return BLUE;
      case 3:
        return GREEN;
      default:
        return null;
    }
  }
}
